openstack/baremetal/kustomization.yaml
openstack/baremetal/overlay1.yaml
openstack/baremetal/resources.yaml
openstack/base/kustomization.yaml
openstack/base/resources.yaml
openstack/base/site-values.yaml
openstack/network/linuxbridge-flat-vlan-vxlan/kustomization.yaml
openstack/network/linuxbridge-flat-vlan-vxlan/overlay1.yaml
openstack/network/linuxbridge-flat-vlan/kustomization.yaml
openstack/network/linuxbridge-flat-vlan/overlay1.yaml
openstack/network/openvswitch-flat-vlan-vxlan/kustomization.yaml
openstack/network/openvswitch-flat-vlan-vxlan/overlay1.yaml
openstack/network/openvswitch-flat-vlan-vxlan/resources.yaml
openstack/network/openvswitch-flat-vlan/kustomization.yaml
openstack/network/openvswitch-flat-vlan/overlay1.yaml
openstack/network/openvswitch-flat-vlan/resources.yaml
openstack/os_release/queens/kustomization.yaml
openstack/os_release/queens/values.yaml
openstack/os_release/stein/kustomization.yaml
openstack/os_release/stein/values.yaml
openstack/output/gate-centos-lb-ceph-aio/openstack.yaml
openstack/site/gate-centos-lb-ceph-aio/kubectlapplyordertransformer.yaml
openstack/site/gate-centos-lb-ceph-aio/kustomization.yaml
openstack/site/gate-centos-lb-ceph-aio/site-values.yaml
openstack/storage/ceph/kustomization.yaml
openstack/storage/ceph/overlay1.yaml
openstack/storage/ceph/resources.yaml
openstack/storage/nfs/kustomization.yaml
openstack/storage/nfs/overlay1.yaml
openstack/storage/nfs/resources.yaml

* convert OpenStack armada manifest into HelmRelease manifest
* split selectable feature into `network/storage/baremetal` overlays from base manifest

[Feature] Implement OpenStack HelmReleases

---

lma/base/kustomization.yaml
lma/base/resources.yaml
lma/base/site-values.yaml
lma/output/dev/lma.yaml
lma/site/dev/kubectlapplyordertransformer.yaml
lma/site/dev/kustomization.yaml
lma/site/dev/site-values.yaml

* transform lma armada manifest into HelmReleases manifest
* defined site-values depending on a site environment.

[Feature] Implement LMA Helmreleases 

---

lma/base/resources.yaml
openstack/base/resources.yaml

* Array, Map 의 default value가 empty여야 올바른 값이 output 으로 나옴
* default value가 [TO_BE_FIXED], {TO_BE_FIXED: TO_BE_FIXED}일 경우 output에 그대로 남게 됨

Fix wrong default vars

---

openstack/base/resources.yaml
openstack/image/image-values.yaml

* HANU CI/CD 환경에 openvswitch chart 배포가 필요하여 base/resources.yaml에 추가

Add openvswitch chart in resources.yaml

---

lma/base/resources.yaml
openstack/base/resources.yaml

* helm version v3에서만 배포 하도록 strict option 추가
* helm version v2에서는 에러가 발생함

fix helm version to v3

---

lma/base/resources.yaml
lma/image/image-values.yaml

* jeju site에 taco-watcher를 띄우기 위해 base resources에 추가

add taco-watcher HelmRelease

---

README.md
render.sh

rename decapod-yaml to decapod-base-yaml

fix repo name to decapod-base-yaml

---

cloud-console/base/kustomization.yaml
cloud-console/base/resources.yaml
cloud-console/base/site-values.yaml
cloud-console/image/image-values.yaml

클라우드 콘솔만 설치할 수 있는 workflow 작성
- cloudconsole + keycloak + postgresql

add cloud-console only from admin-tools

---

.github/workflows/validate.yml
lma/base/resources.yaml
lma/image/image-values.yaml

* main branch target PR에 대해 image-values.yaml 파일을 검증합니다.
* validation error를 github action log로 확인할 수 있습니다.
_먼저 lma에 대해서 검증하고 첫번째 PR을 올리고 openstack, cloud-console 등은 추후 작업해서 별도 PR로 올릴 생각입니다._

new github action for image values validation

---

lma/base/resources.yaml

* eck-resource 1.0.1 차트 버전 사용
* https://github.com/openinfradev/taco-helm/pull/12 머지 이후 적용되야함.

use eck-resource version 1.0.1

---

service-mesh/base/resources.yaml
service-mesh/base/site-values.yaml

* service-mesh-resource 차트 0.1.2버전 업그레이드
* meshConfig, tracing_url관련 설정 추가

upgrade service-mesh-resource to 0.1.2

---

service-mesh/base/resources.yaml

* jaeger query, kiali의 replicas 값을 추가. 
* jaeger collector는 autoscaling 기능으로 동작.

add replicas for jaeger, kiali

---

lma/base/resources.yaml
lma/base/site-values.yaml
lma/image/image-values.yaml

* thanos-config 차트를 통해 thanos object storage secret과 thanos sidecar 의 엔드포인트 들을 등록할 수 있다.

Additional configurations for thanos sidecar

---

README.md
docs/concept.md
docs/quickstart.md

* decapod-site-yaml 사용 부분을 decapod-site로 변경

use decapod-site insteads of decapod-site-yaml

---

lma/base/resources.yaml
lma/base/site-values.yaml

Thanos Compactor
TACO에서는 Compactor 관련하여 다음의 변경가능한 값을 가져간다.
- 최대 자원 사용량 제한
- 노드 지정
- Compaction 실행주기 설정
- Downsampling 종류 설정 및 종류별 저장주기 설정
- Vertical Compaction을 수행할 수 있도록 준비
-- Prometheus HA를 사용할 수 있도록 준비
- compactor 에러시 중단된 블록삭제 설정

TACODEV-731: Thanos compactor config

---

service-mesh/base/resources.yaml
service-mesh/base/site-values.yaml

아래 pull request 내용과 싱크가 맞도록 value override 부분을 업데이트함.
https://github.com/openinfradev/taco-helm/pull/20

update service-mesh-resource config

---

service-mesh/base/resources.yaml

service-mesh-resource 차트의 최신 버전 사용하도록 수정

use service-mesh-resource chart v0.1.9

---

lma/base/resources.yaml

* use lma-addons 1.3.0
* podmonitor namespace selector 추가

monitoring istio v1.9.1

---

lma/base/resources.yaml
lma/base/site-values.yaml

kustomize의 타입체크에 따른 에러 발생부분을 수정하였습니다.

fix wrong config on thanos

---

openstack/base/site-values.yaml

fix helm repo for openstack

---

service-mesh/base/resources.yaml

* jaeger CustomResource의 ingress를 disable한다
* 필요 시에 service-mesh-resource에 추가하여 enable하도록 구현.

disable jaeger's ingress

---

service-mesh/image/image-values.yaml

* 오프라인 환경 설치를 위해 service-mesh의 image-values.yaml을 추가

added image-values of service-mesh resources for the offline environment

---

README.md
cloud-console/base/resources.yaml
docs/quickstart.md
lma/base/resources.yaml
openstack/base/site-values.yaml
service-mesh/base/resources.yaml

* hanu-helm-repo 가 helm-repo로 이름이 변경됨

renamed hanu-helm-repo to helm-repo

---

lma/base/resources.yaml
lma/base/site-values.yaml

https://tde.sktelecom.com/wiki/pages/viewpage.action?spaceKey=TACODEV&title=Uniformed%20Deployment%20for%20The%20Thanos&#
위 페이지에서 정의한 thanos 단일형상 배포관련한 pr

TACODEV-847: uniformed deployment for thanos

---

lma/base/site-values.yaml

test for alertmanager

---

lma/base/site-values.yaml

added federation guideline

---

lma/base/resources.yaml
lma/base/site-values.yaml

elasticsearch와 kibana를 설치하는 eck-operator에 namespace를 만드려는 시도에서 에러가 발생하여 이를 회피하도록 수정

Bugfix eckoperator

---

lma/base/site-values.yaml

add comment on site-value for lma

---

service-mesh/base/resources.yaml

* jaeger-operator에서 사용하는 image들을 override를 위해 upstream 차트를 수정하여 사용한다.

Fix jaeger operator chart

---

service-mesh/base/resources.yaml

service-mesh-resource 차트 버전 업데이트 하였습니다.
참고: https://github.com/openinfradev/helm-charts/blob/e0010a44fc1069e3837a649dcfa48c1e903d699a/service-mesh-resource/Chart.yaml#L9

update service mesh resource chart

---

lma/base/site-values.yaml
openstack/base/site-values.yaml

스토리지 클래스 기본 이름을 'taco-storage'로 변경하였습니다.
관련 논의: https://github.com/openinfradev/taco-gate-inventories/pull/20

use 'taco-storage' for storageclass name

---

tks-cluster/aws/resources.yaml
tks-cluster/aws/site-values.yaml

* cluster.networkSpec 값이 잘못 설정된 것 수정

bugfix: wrong cluster networkSpec

---

tks-cluster/aws/resources.yaml

* https://github.com/openinfradev/helm-charts/pull/57 PR이 먼저 머지되어야 함

bump up cluster-aws-api chart to 0.1.1

---

decapod-controller/base/kustomization.yaml
decapod-controller/base/resources.yaml
decapod-controller/base/site-values.yaml
decapod-controller/image/image-values.yaml

argocd 기반 bootstrapping 대상인 decapod-controller 관련 설정 추가
- prepare-decapod-controller (argo-wf 에서 필요로 하는 secret 생성)
- postgresql
- argo-workflow (v3)

add decapod-controller

---

decapod-controller/base/resources.yaml

* fix argo workflows to argo workflows operator

fix release name

---

decapod-controller/base/resources.yaml
decapod-controller/base/site-values.yaml

postgresql secret이 두 namespace에 만들어져야하므로, app name을 일관성 있게 수정함

modify app names in unified manner

---

decapod-controller/base/resources.yaml

-argo-wf version upgrade
-override auth-mode to 'server'

upgrade argo-wf version to v3.1.9

---

sealed-secrets/base/kustomization.yaml
sealed-secrets/base/resources.yaml
sealed-secrets/base/site-values.yaml
sealed-secrets/image/image-values.yaml

[decapod-issues/16]  sealed-secrets-controller 및 Kubed 설치 자동화를 위해 차트 추가합니다

add sealed-secrets app group

---

lma/base/resources.yaml
lma/base/site-values.yaml
lma/image/image-values.yaml

사용 및 지원을 중단한 taco-watcher 내역을 제거하였습니다.

remove taco-watcher

---

lma/base/resources.yaml

lma: prometheus: fix thanosService

---

decapod-controller/base/resources.yaml

아래 issue 해결을 위해 버전 급히 올립니다.
https://github.com/argoproj/argo-workflows/issues/6766

bugfix: upgrade argo-wf to v3.2.6

---

sealed-secrets/base/resources.yaml

rename sealed-secret-controller to '-operator'

---

lma/base/resources.yaml

bump up fluentbit-operator chart

---

lma/base/resources.yaml

node exporter, process exporter의 네트워크 모드 변경할 수 있도록 내역 추가

switchable hostnetwork on a process-exporter and a node-exporter

---

service-mesh/base/resources.yaml
service-mesh/base/site-values.yaml

tks-portal 을 위한 base yaml 을 추가합니다.
테스트를 위해 테스트 정보를 사용하였습니다.

feature. add tks-portal

---

admin-tools/base/resources.yaml

keycloak-operator-crds 를 추가합니다.

admin-tools: add keycloak-operator-crds

---

tks-cluster-byoh/base/kustomization.yaml
tks-cluster-byoh/base/resources.yaml
tks-cluster-byoh/base/site-values.yaml

tks-cluster-byoh 그룹 및 하위 차트 (cluster-api-byoh만 존재)를 추가합니다.

add tks-cluster-byoh group

---

lma/base/resources.yaml
lma/base/site-values.yaml

- make default values in TACO LMA for fluentbit

fluentbit의 기본값을 TACO LMA형상에 맞도록 수정

---

lma/base/resources.yaml

TOBEFIXED로 고정지정하면 kustomize할때 에러가 발생함..
이에따라 수정해야 하는 값이라도 일단 [ ] 형태의 빈 배열로 지정함

bugfix: escape from kustomize error

---

lma/base/resources.yaml
lma/base/site-values.yaml

minio를 따로 설치하도록 구성했습니다.
decapod-flow와 세트로 변경되어야 합니다.
테스트를 위해 강제 merge하겠습니다.

minio: dedicated installation for shared service(thanos/loki)

---

lma/base/resources.yaml

loki datasource 이름 변경 (grafana에서 loki연동)

fluentbit: change the default loki target

---

lma/base/resources.yaml

grafana dashboard 로딩관련 로직변경 반영

lma-addons: new mechanism for deploing grafana dashboard

---

lma/base/resources.yaml

bump up lma-addons

---

service-mesh/base/resources.yaml

add nodeAffinity for Jaeger component

add jaeger nodeAffinity

---

service-mesh/base/resources.yaml

- add jaeger image url
- add instio ingress gateway image url

add jaeger image and istio-ingress-gateway image url

---

lma/base/resources.yaml
lma/base/site-values.yaml

event-exporter: add a way to configure cluster-name

---

admin-tools/base/resources.yaml
cloud-console/base/resources.yaml
decapod-controller/base/resources.yaml
lma/base/resources.yaml
sealed-secrets/base/resources.yaml
service-mesh/base/resources.yaml
tks-cluster/base/resources.yaml
tks-cluster/infra/aws/resources.yaml
tks-cluster/infra/byoh/resources.yaml

harbor 로 chart repo url 변경
harbor 에는 chart를 업로드 해 놓았음

change original url to tks harbor url

---

.github/workflows/check_chart_repo.sh

chart 저장소를 https://harbor-cicd.taco-cat.xyz/tks로 임의 지정하여 체크하고 있었는데 
실제로 올려진 챠트는  https://harbor-cicd.taco-cat.xyz/chartrepo/tks에 있네요..
이에따라 check로직에서 기준 값 변경합니다

update local chart repository for check

---

lma/base/resources.yaml

change lma images to use local

---

lma/base/resources.yaml

fix prometheus and alertmanager instance image

---

decapod-controller/base/resources.yaml
sealed-secrets/base/resources.yaml
tks-cluster/base/resources.yaml
tks-cluster/base/site-values.yaml
tks-cluster/infra/aws/resources.yaml

- 외부 레지스트리 저장소를 사용하던 이미지들을 내부 Harbor 저장소로 변경하였습니다.
- calico는 오퍼레이터를 통해 설치하도록 변경하였습니다.

Fix missing harbor images

---

tks-cluster/infra/aws/resources.yaml

* https://github.com/openinfradev/helm-charts/pull/175 반영 사항을 사용하기 위한 변경입니다.

update cluster-api-aws to 0.8.2 for multi-tenancy

---

tks-cluster/base/resources.yaml
tks-cluster/base/site-values.yaml

아래 3개를 모두 같이 merge 해야 함
- decapod-base-yaml
- decapod-site
- tks-flow

add argo-rollouts chart

---

lma/base/resources.yaml

typo in alermanager configuration.

---

lma/base/resources.yaml
lma/base/site-values.yaml

default slack channel: openinfradev.slack.com #default-alerts-ep

alert용 slack channel 지정

---

lma/base/site-values.yaml

grafana에 node selector 지정할수 있도록 하고 lma 노드에 배치합니다

grafana: add node selector

---

lma/base/resources.yaml

fluentbit 이미지 변경시 쓰레기 값이 섞여 들어갔습니다. 해당 내역을 삭제합니다.

typo: fluentbit: remove garbage when define image

---

lma/base/resources.yaml

minio: change deploy mode from standalone to distribute

---

lma/base/resources.yaml

minio: change default replicas number to 1

---

lma/base/resources.yaml

thanos-config 버전이 중간과정이어서 올립니다.

bumpup thanos-config

---

lma/base/resources.yaml
lma/base/site-values.yaml
tks-cluster/infra/aws/resources.yaml
tks-cluster/infra/aws/site-values.yaml

release -> main merge (20220808)

release -> main merge (20220808)

---

lma/base/resources.yaml
tks-cluster/base/resources.yaml

fix nodeport # on pushgateway and nginx

---

tks-cluster/base/resources.yaml

remove nodeport definition

---

lma/base/resources.yaml
tks-cluster/base/resources.yaml

main merge ( 20230814 )

---

lma/base/resources.yaml

https://github.com/openinfradev/helm-charts/pull/200 반영하기 위해 차트 버전 업데이트합니다.

update lma-addson chart version

---

tks-cluster/base/resources.yaml

- Minimal deploy support
함께 merge되어야 할 것들
- https://github.com/openinfradev/decapod-site/pull/174
- https://github.com/openinfradev/decapod-base-yaml/pull/262
- https://github.com/openinfradev/tks-flow/pull/251

최소사항 클러스터 지원을 위한 여정

---

policy/base/kustomization.yaml
policy/base/resources.yaml
policy/base/site-values.yaml

- https://github.com/openinfradev/tks-flow/pull/256
- https://github.com/openinfradev/decapod-flow/pull/130
- https://github.com/openinfradev/decapod-base-yaml/pull/265
- https://github.com/openinfradev/decapod-site/pull/178
- https://github.com/openinfradev/helm-charts/pull/206
다른 파일 수정없이 policy 앱을 추가한 내역입니다,

policy: add a decapod app for policies

---

tks-admin-tools/base/resources.yaml

release name 을 tks-apis 로 변경합니다.

bugfix. change release name to tks-apis

---

lma/base/site-values.yaml

thanos -> tks-thanos
minio -> tks-minio

Minio의 버킷 생성 명 변경

---

lma/base/resources.yaml

loki가 사용할 버킷명 수정.. 이미 버그상태였습니다.

change default loki's bucket name from loki to tks-loki

---

tks-cluster/base/site-values.yaml

https://github.com/openinfradev/decapod-base-yaml/pull/276 에서 누락된 삭제 부분을 추가합니다.

remove unused cluster-autoscaler values

---

tks-admin-tools/base/resources.yaml

2023.11.01 SKB 환경에서 admin cluster 2차 구축 과정에서 나온 필요 수정 사항을 반영하였습니다.

minor modification for skb installation

---

service-mesh/base/resources.yaml
service-mesh/base/site-values.yaml

Jaeger의 SSO를 위해 gatekeeper를 추가합니다.

Jaeger SSO 기능 추가

---

lma/base/resources.yaml

minio: change value key

---

lma/base/resources.yaml

배포된 etcd 형상에 맞게 서비스 모니터 설정을 변경합니다.

lma: fix etcd servicemonitor

---

tks-cluster/base/resources.yaml

argo-rollout: metrics

---

tks-cluster/infra/aws/resources.yaml

resolve conflict

---

lma/base/resources.yaml

fluent-operator: bump up operator to support more input methods

---

lma/base/resources.yaml

opa관련 모니터링을 위한 exporter 초기버전 추가
- https://github.com/openinfradev/decapod-base-yaml/pull/311
- https://github.com/openinfradev/decapod-flow/pull/139

opa-exporter: add exporter for opa

---

lma/base/resources.yaml

trivial. fix typo

---

policy/base/resources.yaml

policy-serving: enable to log denies

---

tks-admin-tools/base/site-values.yaml

20240517 develop to release ( v4.0.0 )

20240517 develop to release ( v4.0.0 )

---

tks-cluster/infra/aws/resources.yaml
tks-cluster/infra/aws/site-values.yaml

extenral aws cloud provider (aws-cloud-controller-manager) 사용을 위해 차트 정보를 추가합니다.

Add external aws cloud provider

---

tks-cluster/infra/aws/resources.yaml

InPlaceResizing 위한 차트 버전 및 k8s 버전 업데이트

update cluster-api-aws chart & k8s version

---

lma/base/resources.yaml

apply new render: lma is done

---

lma/base/resources.yaml

lma: add parameter on resource.yaml

---

service-mesh/base/resources.yaml

서비스메시에서 lma에 연결하는 부분의 네임스페이스 변경

servicemesh: flexible namespace for LMA
