- lma/base/resources.yaml
- lma/image/image-values.yaml
이전 버전의 helm chart 들이 업그레이드 되어 이렇게 맞춥니다.
참고로 hanu-helm-repos는 그냥 master에 push해서 등록했습니다. (기존 내역 수정은 없고 추가만 함)
> align with new env. on github.com

- admin-tools/base/resources.yaml
- lma/base/resources.yaml
- lma/base/site-values.yaml
- openstack/base/resources.yaml
* In kustomize v3.8.7, strict type checking is enabled.
* So it has to be same type of HelmRelease values in resources.yaml as output.yaml.
> fix: change undefined helm values to correct types

- lma/base/resources.yaml
hipchat 지원 사라지면서 기존 들어있던 내역에 문제를 일으킴
> prometheus-alertmanager does not support hipchat anymore

- lma/base/resources.yaml
* default value 가 TO_BE_FIXED면 boolean이 아닌 string으로 인식하여, kustomize build이후에 "true", "false"로 치환된다.
* resources.yaml의 boolean 기본 값은 true 혹은 false로 정의
> [Bugfix] fix default boolean value

- lma/base/resources.yaml
tacoplay에서는 coredns가 기본으로 사용되며, kubedns를 사용하고 있지 않기때문에 kubedns를 모니터링할 필요가 없습니다.
따라서 prometheus의 모니터링 대상에서 `kubedns: false`로 변경합니다.
> disable kubedns as default

- lma/base/resources.yaml
- lma/base/site-values.yaml
- lma/image/image-values.yaml
Use eck-operator and eck-resource chart instead of the elasticsearch-operator.
> use eck-operator and eck-resource chart

- lma/base/resources.yaml
* fluentbit-operator chart를 1.0.10으로 업데이트
* 1.0.10버전에서는 fluentbit cr-cm과 job-es-template의 helm hook-delete-policy 관련 문제가 수정됨
> Bump fluentbit-operator chart up to 1.0.10

- lma/base/resources.yaml
* elasticsearch test를 위해 직접 elasticsearch와 통신이 필요함. 외부통신을 위한 nodePort를 open한다.
> add nodePort to elasticsearch

- docs/quickstart.md
- decapod-base-yaml 볼륨 마운트 시 상대경로를 사용하면 에러가 발생. 절대경로로 변경
- openstack의 경우 base폴더가 빠져있어 이를 추가
> Fix render decapod-base-yaml

- lma/base/resources.yaml
* es `9200` port는 hotdata, master, http가 공통으로 갖는다.
* http의 nodePort 30002로 세팅하고 싶지만 targetPort가 모두 9200으로 같아서 설정상 어떻게 해도 적용이 안되는 느낌.
* 따라서 type: NodePort로만 설정하면 다음과 같이 랜덤하게 nodePort가 잘 적용된다.
```
eck-elasticsearch-es-hotdata          ClusterIP   None            <none>        9200/TCP             30m
eck-elasticsearch-es-http             NodePort    10.233.5.88     <none>        9200:30928/TCP       16m
eck-elasticsearch-es-master           ClusterIP   None            <none>        9200/TCP             30m
```
* random 하게 설정된 nodePort를 가져오도록 validate-lma job을 수정함
> bugfix: can't specify nodePort

- lma/base/resources.yaml
- lma/base/site-values.yaml
- service-mesh/base/kustomization.yaml
- service-mesh/base/resources.yaml
- service-mesh/base/site-values.yaml
* istio, jaeger, kiali를 설치하는 service-mesh application 을 정의
* 기존 LMA에 istio, jaeger를 monitoring할 수 있도록 prometheus, grafana, elasticsearch 연동
> Add service-mesh applications

- service-mesh/base/resources.yaml
* istio-system namespace를 helm-operator가 만들어주는데, 이때문에 istio-operator에서 istio-system namespace를 또 만들려고 해서 에러가 발생함.
* helm release의 namespace만 istio-operator namespace로 바꿈.
> fix: failed to install istio-operator

- lma/base/resources.yaml
* kube-prometheus-stackd으로 차트가 바뀌면서 prometheus-operator 서비스 명이 proemtheus-operator-kube-p-operator로 변경됨..
* 이를 수정하기 위해 fullnameOverride 변수를 prometheus-operator로 변경
> fix: override fullname of prometheus-operator

- lma/base/resources.yaml
- lma/base/site-values.yaml
Federation Grafana에서 연동하는 데이터 소스를 Fed-prometheus가 아닌 Thanos로 변경하는 내용입니다.
> Use Thanos for Fed-Grafana Datasource

- service-mesh/base/resources.yaml
* 0.1.7 차트는 hanu-helm-repo에 없습니다. 최신 버전인 0.1.8을 사용하도록 변경하였습니다.
> use service-mesh-resource 0.1.8

- lma/base/resources.yaml
- lma/image/image-values.yaml
* thanosService의 NodePort 지원안되던 이슈 고친 차트로 적용
> update kube-prometheus-stack to 14.5.0

- lma/base/resources.yaml
- lma/base/site-values.yaml
https://tde.sktelecom.com/wiki/display/TACODEV/Query-frontend
> TACODEV-733: manageability for Query frontend

- lma/base/resources.yaml
* eck-resource 1.1.0버전을 사용하도록 수정
* 이전 버전에서 elasticsearch CRD의 http 설정이 잘못 들어가있었음
> use eck-resource 1.1.0 version

- lma/base/resources.yaml
- service-mesh/base/resources.yaml
* eck-operator를 만들 때 elastic-system namespace도 같이 만들도록 수정. (argo cd에서 namespace를 만들어 주지 않는다.)
* istio-operator의 namespace는 istio-system으로 수정. (istio-operator namespace를 만들지 않기 때문에 namespace already exists. 문제가 자동 해결됨)
> fixes for argocd

- lma/base/resources.yaml
- service-mesh/base/resources.yaml
* Elasticsearch NodePort 30002는 thanos minio의 nodePort와 겹친다. 그래서 30011번으로 수정
* lma-addons차트 1.4.0에서 namespace를 만들 수 있게 되었다. fed namespace를 만들게 한다. (argoCD로 설치시 fed namespace가 생성되지 않아서 문제 발생)
* kiali-operator의 istio-namespace 값은 실제 존재하는 namespace여야한다. 따라서 istio-system으로 변경한다.
> Fix some bugs

- lma/base/site-values.yaml
* max_size와 max_size_items 값이 바뀌어서 변경
* query frontend의 log-queries-longer-than에 unit이 없으면 에러가 발생. 유닛 추가
> fix bugs in thanos config

- service-mesh/base/resources.yaml
- service-mesh/base/site-values.yaml
along with https://github.com/openinfradev/helm-charts/pull/37
* istio-operator controller 자체는 별도의 namespace에 뜨도록 함.
* default gateway 명칭 변경
> update service-mesh configs

- service-mesh/base/resources.yaml
차트에서 istio-system namespace 생성하도록 value override.
> service-mesh-resource: create istio-system ns

- lma/base/resources.yaml
kibana에서 elasticsearch를 연결할때 https라는 포트를 찾고 있는데 해당 서비스의 포트에는 http만 존재하여 찾지못함
http라고 명명된 포트는 실제로 https (tls) 통신을 하고 있으므로 명칭을 바꿔주는 것은 문제 없어 보임
따라서 본 PR을 통해 해결하고자 함
> eck-operator search the port name "https"

- lma/base/resources.yaml
30007 포트를 prometheus sidecar의 default 노드포트로...
> Default port 30007 for prometheus sidecar in TACO LMA

- service-mesh/base/resources.yaml
- service-mesh/image/image-values.yaml
* 빠져있는 service mesh의 image 값 추가
* Upstream jaeger-operator 차트는 image override를 할 수 없어 차트를 수정하여 사용
> Update jaeger operator chart and image values

- lma/base/resources.yaml
- lma/base/site-values.yaml
* fed namespace 사용이 없어지면서 addons / fed-addons를 구분할 필요성이 없어짐.
* addons 안에 fed-addons 내용을 추가하여 fed-addons는 삭제
> merged addons and fed-addons

- lma/base/resources.yaml
- lma/base/site-values.yaml
1. thanos 질의가 수행되지 못하게 되었던 버그 수정
2. prometheus내부의 thanos-sidecar에 대한 중복생성 이슈해소
> bugfix: thanos-sidecars handle raw data within 3h

- admin-tools/base/resources.yaml
- cloud-console/base/resources.yaml
- lma/base/resources.yaml
- openstack/base/resources.yaml
- service-mesh/base/resources.yaml
내용
현재 사용하는 manifest는 helm repo에 저장된 chart를 기반으로 돌아가도록 되어있다.
개발의 편의성을 위해 github이나 local에 올라간 소스를 기반으로 배포하는 것을 위한 유틸리티가 있다면 좋겠다.
수행내역
spec.chart를 재정의해서 필요한 기능을 수행할수 있도록 제반 유틸리티 수정
type: helmrepo
repository: https://prometheus-community.github.io/helm-charts
name: kube-prometheus-stack
version: 14.5.0
또는
type: git
repository: git@github.com:helm/charts
name: charts/stable/prometheus-operator
version: master 
와 같이 정의 가능하고 type은 생략할 수 있고 기본값 helmrepo로 산정되어 작업됨
type이 git이면 repository는 git 과 같은 의미 name은 path와 같은 의미 version은 ref와 같은 의미로 동작하도록 한다.
산출물
https://github.com/openinfradev/decapod-site/pull/33
https://github.com/openinfradev/decapod-base-yaml/pull/87
https://github.com/openinfradev/kustomize-helm-transformer/pull/30
> TACODEV-858: support a github directory as the location of helm charts

- service-mesh/base/resources.yaml
- service-mesh/base/site-values.yaml
- service-mesh/image/image-values.yaml
helm-chart 가 먼저 수정되어야 함.
관련 PR : [openinfradev/helm-charts/pull/48]
Istio operator chart version: 1.10.2
Kiali operator chart version: 1.34.0
Jaeger operator chart version: 2.20.0
decapod-site 와 servicemesh workflow 도 같이 수정되어야 함
> servicemesh refacotring

- .github/workflows/render.sh
- .github/workflows/validate.yml
- tks-cluster/aws/kustomization.yaml
- tks-cluster/aws/resources.yaml
- tks-cluster/aws/site-values.yaml
* tks-cluster app group 추가
* cluster-api-aws, cluster-api-openstack 등의 kubernetes cluster provisioning을 위한 구성 정보를 담는다.
* 현재는 cluster-api-aws만 추가
> Added new app group tks-cluster

- lma/base/resources.yaml
* eck-operator가 설치될 namespace를 만들어줘야함. (decapod v2에서는 namespace생성이 필요하기때문에)
* eck-operator helm chart의 createOperatorNamespace 변수로 namespace 생성 가능
> creates namespace for eck-operator

- lma/base/resources.yaml
- lma/base/site-values.yaml
fed-master의 역할 중 필요한 부분에 대한 prometheus로 이동
- alertmanger 기동 및 rule연동 설정 
- fed-master 제거
- thanos의 alert manager 타겟변경
grafana의 thanos 연동
서비스 모니터링 버그 수정
- node-exporter와 kube-state에 대한 서비스 모니터 on
> TACODEV-798: remove fed-master

- lma/base/resources.yaml
- lma/image/image-values.yaml
LMA 서비스에 필요한 master node에서 etcd secret을 생성하는 prepare-etcd-secret 차트의 대한 base yaml입니다.
> Add prepare-etcd-secret

- lma/base/resources.yaml
https://github.com/openinfradev/helm-charts/pull/66 의 decapod-base-yaml 적용입니다.
> Upgrade eck-resource helm chart to 1.1.1

- decapod-controller/base/resources.yaml
expression tag template이라는 new feature를 사용하기 위해 argo workflows v3.1.0 을 사용해야 함.
> override argo image tag

- lma/base/resources.yaml
- lma/image/image-values.yaml
API 변경 사항에 대응하기 위해 아래 차트들에 대한 업그레이드를 수행하였습니다.
prometheus-operator: 14.5.0 -> 21.0.3
eck-operator: 1.6.0 -> 1.8.0
eck-resource: elastisearch 버전 변경 (7.5.1 -> 7.15.2)
> Update for kube 1.22

- lma/base/resources.yaml
- lma/base/site-values.yaml
https://github.com/openinfradev/tks-issues/issues/43
Promtail 차트의 (거의) 최신 버전인 3.9.1 차트를 살펴보니, scrapeConfig 설정 부분에 nodeName label이 추가되어서, 별도로 이 부분을 override할 필요가 없어졌습니다.  단, 차트의 value structure가 살짝 바뀌어 loki server address를 적절한 값으로 override해주어야 하기에 해당 내용 추가하였습니다.
> override loki address to fit latest promtail chart

- lma/base/resources.yaml
1.22 버전을 지원하기 위한
- fluentbit-operator 변경: helm chart, docker image 등 기반 내역은 수동으로 올려진 상태입니다.
- process-exporter 변경
---
k8s 버전이 1.22 로 올라가면서 API 변경된 부분이 있어 현재 TKS에서 사용 중인 일부 chart들이 제대로 동작하지 않으므로, API 스펙에 맞도록 chart 변경이 필요함
산출물
* 수정된 decapod-base-yaml 코드
> k8s v1.22 버전 지원

- lma/base/resources.yaml
devopsprodigy-kubegraf-app 플러그인이 Grafana v8 에서 동작하지 않기 때문에 제거합니다.
- https://github.com/devopsprodigy/kubegraf/issues/62
Grafana 8에서 동작하는 구현이 v2라는 이름으로 개발 중 (https://github.com/devopsprodigy/kubegraf-v2) 이긴 한데 정식 릴리즈는 되지 않았고 직접 플러그인을 빌드해야 합니다.
- https://github.com/devopsprodigy/kubegraf-v2/issues/1#issuecomment-989800770
- https://github.com/devopsprodigy/kubegraf/issues/68#issuecomment-939680310
> lma: grafana: remove devopsprodigy-kubegraf-app plugin

- lma/base/resources.yaml
https://github.com/openinfradev/tks-issues/issues/106
* as-is: default로 /var/log/pods/ 아래의 로그 파일만 수집
* to-be: /var/log/messages 파일까지 수집하기 위해, 차트의 volume 및 volumeMount 값을 override하여 /var/log 전체를 마운트하도록 변경
추가로, hostname 값을 label로 추가하기 위해, cmd line argument 추가하였습니다.
> Loki로 syslog 수집

- .github/workflows/validate.yml
- lma/base/resources.yaml
https://github.com/openinfradev/decapod-base-yaml/pull/135 에서 작업했던 내용 다시 올립니다 (기존 PR 의 코드 내용이 바뀌었으니 그부분 말고 대화 부분만 참고하세요)
wikimedia chart 는 그대로 사용하고, openshift  측 repo (https://github.com/openshift/eventrouter) 의 Dockerfile 로 이미지 빌드하여 "sktdev" repo에 올리고, 해당 이미지 사용하도록 base-yaml에서 override하였습니다. (관련 history는 위의 기존 PR 에 적혀있습니다)
openshift 에서 코드를 많이 수정한 게 아니라서 이 조합도 정상적으로 잘 동작하는 것으로 보입니다.  Openshift의 코드 업데이트가 현재는 거의 멈춰있는데, 만약 다시 변경이 활발히 일어난다면 SKT 자체적으로 주기적인 이미지 빌드 파이프라인 구축도 고려해보려 합니다.
> Loki 로 k8s event 수집

- lma/base/resources.yaml
차트 버전 6.17.4 에서 사용하는 이미지의 경우 계속 crash 되는 증상이 있어 버전 업그레이드합니다.
> upgrade grafana chart to 6.19.4

- lma/base/resources.yaml
https://github.com/openinfradev/helm-charts/pull/92 반영 내용을 사용하기 위해 차트 버전을 업데이트하였습니다.
> update prepare-etcd-secret version

- service-mesh/base/resources.yaml
- service-mesh/base/site-values.yaml
- service-mesh/image/image-values.yaml
- istio operator 는 upstream chart 를 가져와서 openinfradev/helm-repo 에 저장 (app version: 1.11.7, chart version: 1.7)
- jaeger operator 는  upstream chart 를 가져와서 openinfradev/helm-repo 에 저장 (app version: 1.24.0, chart version: 2.23.0)
- kiali operator 는 upstream chart 를 그대로 활용 (chart 버전이 0.0.0 으로 되어 있어서 이전 방법을 그대로 따름) (app version: 1.38.1, chart version: 1.38.1)
> upgrade istio: v1.11.7, jaeger: 1.24.0,  kiali: v1.38.1

- service-mesh/base/resources.yaml
- service-mesh/base/site-values.yaml
- service-mesh/image/image-values.yaml
Change istio operator to istio helm charts
Upgrade charts
- istio-1.13.1
- jaeger-operator-2.27.1 (app: v1.29.1)
- kiali-operator-1.45.1 (app: v1.45.1)
- istio-grafana-dashboard-1.13.1
> Upgrade service-mesh version

- lma/base/resources.yaml
- lma/base/site-values.yaml
kube-prometheus-stack 차트는 POD로 실행되는 etcd의 exporter 아이피를 서비스 셀렉터를 통해 자동 구성하는 방법을 지원합니다. 이를 위해 kubeEtcd.endpoints 리스트가 비어 있어야 하기 때문에 해당 내용으로 정리하였습니다.
> lma: prometheus: fix kubeetcd endpoints

- lma/base/resources.yaml
- lma/base/site-values.yaml
https://github.com/openinfradev/tks-issues/issues/221
thanos에서 타 클러스터의 sidecar LB endpoint를 직접 참조하므로, 사용하지 않는 dns discovery 기능을 disable합니다.
> disable dns discovery of thanos sidecar service

- tks-cluster-aws/base/kustomization.yaml
- tks-cluster-aws/base/resources.yaml
- tks-cluster-aws/base/site-values.yaml
https://github.com/openinfradev/tks-issues/issues/234
관련 PR: https://github.com/openinfradev/tks-flow/pull/87
> merge custom-base-yaml

- lma/base/resources.yaml
https://github.com/openinfradev/helm-charts/pull/125 반영된 내용을 사용하기 위해 kube-state-metrics와 thanos 차트 저장소를 openinfradev로 변경합니다.
> lma: use downstream charts for thanos and kube-state-metrics

- tks-cluster-aws/base/resources.yaml
- tks-cluster-common/base/resources.yaml
local-path를 taco-storage로 사용하기 위한 챠트를 추가합니다.
인프라를 byoh로 지정한 경우 기본으로 설치됩니다.
다음 pr이 함께 merge되야 합니다.
- https://github.com/openinfradev/decapod-base-yaml/pull/166
- https://github.com/openinfradev/tks-flow/pull/102
> install local-path-provioner for a byoh cluster

- lma/base/resources.yaml
- lma/base/site-values.yaml
multiline을 지원하는 paser를 enable하고 요구사항에 의해 개발된 다수의 es클러스터를 지원하는 1.3.0챠트를 사용하도록 함
> lma.fluentbit: support multiline and multi-es

- lma/base/resources.yaml
- lma/base/site-values.yaml
TACO LMA 로깅의 백엔드 선택기능 추가
다음 세가지 pr이 동시에 merge 되어야 함
- https://github.com/openinfradev/decapod-site/pull/95
- https://github.com/openinfradev/decapod-base-yaml/pull/170
- https://github.com/openinfradev/decapod-flow/pull/98
> TACO LMA 로깅의 백엔드 선택기능 추가 

- lma/base/resources.yaml
1. Syslog용 파서 추가
2. fluentbit crd변경 반영 (kubesphere -> fluent)
3. fluent-operator 변경하면서 value구조 바뀌어 이것도 반영
다음 내역이 동시에 merge 되어야 합니다.
https://github.com/openinfradev/helm-charts/pull/142
https://github.com/openinfradev/decapod-base-yaml/pull/172
> fluentbit crd변경 반영 

- lma/base/resources.yaml
- lma/base/site-values.yaml
Loki 상용환경을 위한 형상정의 및 적용
1. chart변경: form single-mode to micro service mode
2. 맞춰서 값지정
3. loki의 obj store로 minio 사용하도록 변경 (thanos에서 설치하는 minio)
cf. commit중 첫번째 부분은 s3 활용을 위해 시도했던 부분으로 몇몇 이유에 의해 현재 활용 불가한 상황을 포함함.. 추후 s3를 활용할 경우 참고 할수 있도록 남겨둠.
> Loki production

- lma/base/resources.yaml
- lma/base/site-values.yaml
unittest 실패의 이유로 보이는 내용을 변경합니다.
merge 후 내일 e2e 테스트 결과를 보겠습니다.
> bugfix. disable kibana-init

- lma/base/resources.yaml
log수집에서 지속적인 에러가 발생
```
[2022/12/01 06:51:41] [error] [output:loki:loki.0] loki-loki-distributed-gateway.lma.svc:80, HTTP status=413
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.19.10</center>
</body>
</html>
```
이를 해결하기 위한 loki의 frontend 설정 추가하는 내역
loki의 내부 컴포넌트간 처리도 필요하지만 그렇게 하기위해서는 챠트구조가 매우 많은 부분을 override해야함.
테스트 환경에서 현재 플랫폼 로그(kube-system/taco-system/lma/istio...)에 대해서는 해결되는 것처럼 보이므로 일단 pr
내부 컴포넌트간 문제가 발생시 새로운 PR로 대응할 예정 
- fluentbit에 버퍼에 쌓인 데이터를 주기적으로 넣으면서 1M인 기본 제한을 넘겨 데이터를 올리는 경우가 발생
- 한번 밀리기 시작하면 지속적으로 발생하고 fluentbit은 로그수집을 정지했다 시작했다를 반복함
- fluentbit의 컴포넌트별로 이상동작을 발생시킴
- emitter error등 
```
[2022/12/01 06:54:47] [error] [input:emitter:alertrule_match] error registering chunk with …
```
> loki: add nginx config to recieve massive data

- service-mesh/base/resources.yaml
- add pilot image url
- add kiali nodeSelector
> add pilot image url

- tks-cluster/infra/aws/resources.yaml
https://github.com/openinfradev/helm-charts/pull/165 사용을 위해 차트 버전을 업데이트 합니다.
> clustar-api-aws 정적 워커 노드 배포

- tks-cluster/infra/aws/resources.yaml
cluster-api-aws Helm 차트 버전을 EKS 지원이 추가된  0.8.0으로 업데이트하였습니다.
- 참고: https://github.com/openinfradev/helm-charts/pull/166
> update cluster-api-aws to 0.8.0 for EKS

- tks-cluster/infra/aws/resources.yaml
EKS addons 설정 내용이 추가된 cluster-api-aws 차트를 사용하도록 변경합니다.
- https://github.com/openinfradev/helm-charts/pull/169
> update cluster-api-aws for eks addons

- lma/base/resources.yaml
- lma/base/site-values.yaml
- 배경:
-  Arm64 플랫폼 지원을 위해 minio-official/minio의 helm chart를 사용 예정 
- 수정사항:
- minio resource
- bitnami/minio Chart 기반 -> minio-official/minio Chart 기반으로 수정
- Bucket ( /loki 와 /grafana )이 정상 생성되도록 user 추가
- fluentbit resource
- (logalert-exporter) enabled 필드 값을 false로 수정
> feature: Change minio values to support Arm64 platform openinfradev/tks-issues#500

- lma/base/resources.yaml
- lma/base/site-values.yaml
primary cluster의 적용을 위해 기반 형상을 정의 한다.
- 기본 형상을 single로 정의
- prometheus <- grafana의 형태로 매트릭 조회
- 클러스터내 loki <- grafana의 형태로 로그 조회
- 위 설정관련 내역중 loki나 prometheus를 변수로 처리하여 primary 설정에서 해당 변수를 변경하여 처리할 수 있도록 함
- thanos형상도 하나로 통일 (primary 변수 제거)
- 모든 클러스터는 연합형상을 갖고 있지만 primary로 지정한 클러스터에만 thanos 배포
> change default for single cluster

- lma/base/resources.yaml
- lma/base/site-values.yaml
기본 minio의 메모리 request값을 하향 조정함.
16Gb -> 1Gb
> minio: Reduce default request memory size 16->1GB

- lma/base/resources.yaml
prometheus-operaror 이미지 정의가 잘못되어 있는 부분(registry 항목이 repository와 별도로 분리되어 있으나 한꺼번에 정의되어 있음)을 수정합니다.
> lma: fix prometheus-operator images

- lma/base/resources.yaml
kube-state-metrics 이미지를 별도로 정의하지 않고 Helm 차트 기본 값을 그대로 사용합니다.
> lma: user helm chart's default tag for kube-state-metrics image

- tks-cluster/infra/aws/resources.yaml
CAPA 클러스터 POD CIDR 기본 값을 192.168.0.0/16 으로 변경합니다.
> cluster-api-aws: change default POD CIDR

- tks-cluster/infra/aws/resources.yaml
- tks-cluster/infra/aws/site-values.yaml
s3자원에 대한 선언적 관리를 위한 ACK를 추가합니다.
모두 함께 merge되어야 함
- helm: https://github.com/openinfradev/helm-charts/pull/173
- decapod-base: https://github.com/openinfradev/decapod-base-yaml/pull/209
- decapod-site: https://github.com/openinfradev/decapod-site/pull/121
- tks-flow: https://github.com/openinfradev/tks-flow/pull/150
> add ack for s3

- lma/base/resources.yaml
- lma/base/site-values.yaml
- 현재: grafana → thanos 구조를
- grafana → prometheus 구조로 바꿔줘야함
- 다음 변수를 사용하여 global에서 지정하여 사용
- grafanaDatasourceMetric
> primary cluster 체계를 위한 기본값 변경

- tks-cluster/base/resources.yaml
> tks-cluster: ingress-nginx: remove unnecessary service port

- tks-cluster/infra/aws/resources.yaml
Cluster API Provider AWS의 클러스터 버전 기본 값을 v1.25.9 로 변경합니다.
> tks-cluster: aws: update k8s version to v1.25.9

- tks-cluster/infra/aws/site-values.yaml
bucket 이름을 고정으로 변경
현재 primary 구조에서는 organization별 bucket을 생성하고 (현재상황) organization은 계정과 같은 개념이므로 고정명으로 사용가능
추후 organization을 논리적 개념으로 가져가면서 하나의 계정에 여러개 생성가능하도록 하면 이에 대한 수정이 필요한데 현재 organization을 전달하므로 그냥 사용하면 될듯
> ACK: update bucket name

- tks-cluster/base/resources.yaml
- tks-cluster/base/site-values.yaml
cluster-autoscaler Helm 차트(https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler)를 추가합니다.
cluster-autoscaler 적용 당시에 cluster-api 클라우드 프로바이더 구성의 경우 Helm 차트 지원이 미흡해서 별도 Helm 차트를 만들어서 사용해었고 (https://github.com/openinfradev/helm-charts/tree/main/cluster-autoscaler) aws 클라우드 프로바이더 사용을 위해 추가하는 것입니다.
기존 cluster-autoscaler 차트와 이름이 겹치기 때문에 항목 이름을 k8s-cluster-autoscaler로 사용하였습니다.
> add upstream cluster-autoscaler chart

- lma/base/site-values.yaml
alertmanager 에서 멀티 라우트 삭제하면서 발생한 버그해결
> prometheus: override alertmanager config for multiple routes

- tks-cluster/infra/aws/resources.yaml
https://github.com/openinfradev/helm-charts/pull/186 반영된 내용 사용을 위해 수정하였습니다.
> tks-cluster: aws: use cluster-api-aws chart v0.8.3

- lma/base/resources.yaml
fluentbit agent를 최신으로 올려줍니다.
- 기존 v1.8 
- 신규 v2.1
참고로 기존 이미지에는 kst 지원을 위한 parser를 추가했었으나 (i*k 지원)
현재 해당 내역이 필요치 않은 관계로 일단 fluentbit operator의 공식 이미지를 사용
> fluent-resource: using fluentbit agent - v2.1.4

- lma/base/site-values.yaml
loki에 저장되는 객체에대한 만료를 설정합니다.
- thanos: 90일
- loki: 15일
> minio: add default ilm

- lma/base/resources.yaml
- ref: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#urgent-upgrade-notes
1.20에서 마스터를 지칭하는 라벨이 바뀌었네요. 
aws에서 eks 위주로 작업하는 현재는 발현되지 않지만 vm에  cluster 설치하면 발생하고 byoh 작업시에도 만나게 될 예정입니다.
이에 따라 수정해 놓는 것이며 **주의 사항으로 site별로 이 값을 다시 override**하고 있는데 이 내용도 과거버전의 라벨을 지칭하고 있습니다.
따라서 필요한 타이밍에는 수정이 필요
> prepare-etcd-secret: apply the label changes after v1.20

- lma/base/site-values.yaml
minio의 post job을 만들기위한 value의 깊이가 다르게 되어 있는 버그 수정
> minio: bugfix for value level

- lma/base/resources.yaml
distribute 버전으로는 바로 설치가 안되네요.
이에따라 현재 문제를 일으키는 부분을 해소하는 방향으로 전환
> minio: change update strategy to avoid competition for pvc

- lma/base/resources.yaml
버킷이 비워지지 않아서 클러스터가 삭제되지 않는 버그에 대한 수정입니다.
다음 내역이 한꺼번에 merge되어야 합니다.
- https://github.com/openinfradev/helm-charts/pull/194
- https://github.com/openinfradev/decapod-base-yaml/pull/252
- https://github.com/openinfradev/decapod-site/pull/166
> ack-resources: add controllerability for versioned objects on s3 buckets

- lma/base/resources.yaml
argocd에서 완료를 파악하지 못하는 이슈 해소를 위한 오퍼레이터 업그레이드
이미지도 모두 harbor에 등록완료
```
docker pull quay.io/prometheus/alertmanager:v0.25.0
docker pull registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6
docker pull quay.io/prometheus-operator/prometheus-operator:v0.66.0
docker pull quay.io/prometheus-operator/prometheus-config-reloader:v0.66.0
docker pull quay.io/prometheus/prometheus:v2.45.0
docker pull quay.io/thanos/thanos:v0.31.0
docker tag quay.io/prometheus/alertmanager:v0.25.0 harbor-cicd.taco-cat.xyz/tks/alertmanager:v0.25.0
docker tag registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6 harbor-cicd.taco-cat.xyz/tks/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6
docker tag …
```
> kube-prometheus-operator: bumpup due to update function for status

- tks-admin-tools/base/kustomization.yaml
- tks-admin-tools/base/resources.yaml
- tks-admin-tools/base/site-values.yaml
- tks-admin-tools/image/image-values.yaml
https://github.com/openinfradev/tks-issues/issues/861
일단 요렇게 올렸는데, 몇가지 의견을 구할 점들이 있습니다.
1. site-values.yaml 파일의 필요 여부: 만들다 보니 resources.yaml 중 어떤 내용들이 site-values로 가야하는지 상당히 애매하군요. 기본적으로 base의 내용은 다 override할 수 있다고 생각하고 바로 site-template 등에서 직접 override하는 게 나은 건 아닌가 하는 생각도 들었습니다.  opensource 일 때는 사용자가 참고할 수 있는 sample 용도의 성격이 있었으나, 지금처럼 우리가 직접 site-template을 관리하는 상황에서는 그 필요성이 크게 없어진 것 같다는 느낌입니다. 
2. password 값 표시 위치: helm chart 는 공적인 성격의 repo다 보니 password 표시는 자제하자고 태규님께도 코멘트 드렸지만, 실제 값이 들어가는 decapod 입장에서는 어딘가에 실제 값이 들어가야 하는데, 그게 base에서부터? 또는 site 에만? 하는 고민이 되었는데, 일단은 기존 파일들과 비슷하게 base에 다 넣긴 했습니다. 
3. site-values.yaml 과 실제 site-template 에서의 작성 규칙
"a.b.c" 처럼 한줄로 표시하는 형식과 base와 동일하게 block 형식으로 작성하는 형식 중 최종 합의된 rule이 뭐였죠? 전에 동규님께서 이부분 파싱 작업할 때 이슈가 있어 앞으로는 어떻게 하자고 합의했던 걸로 기억해서 다시 여쭤봅니다. 
의견 …
> add tks-admin-tools group

- tks-admin-tools/base/resources.yaml
ingress-ngnix 를 tks-admin-tools 그룹에 복사합니다. 
nodeSelector 및 namespace 등 설정이 usercluster 배포 시와는 다르므로 별도의 entry가 필요합니다.
다음 PR도 함께 머지되어야 합니다
https://github.com/openinfradev/decapod-site/pull/179
> Clone ingress nginx

- tks-cluster/base/resources.yaml
Mananged Control plane과 EKS 각각 분리해서 사용하던 cluster-autoscaler 차트를 업스트림 차트(https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler)로 통일합니다.
- 이력
- Managed controle plane: cluster-api 프로바이더 지원을 위한 내역이 부족하여 업스트림과 별도로 차트를 만들어서 사용 (https://github.com/openinfradev/helm-charts/tree/main/cluster-autoscaler)
- EKS: AWS 프로바이더를 사용하여 적용
최신 버전에서는 cluster-api 프로바이더를 위해 필요한 부분도 모두 포함되어 있어 업스트림 차트를 공통적으로 사용하도록 수정
> make the upstream cluster-autoscaler chart common to all

- tks-cluster/infra/aws/resources.yaml
aws-ebs-csi 드라이버 차트를 업데이트 합니다.
주요 변경 이유는 K8S v1.25 부터 PodDisruptionBudget의 apiVersiond이 beta가 제거된 것입니다. 관련 내용이 반영된 최신 바전을 사용하도록 합니다.
> update aws-ebs-csi chart to v2.24.0

- lma/base/resources.yaml
lma-addons chart에 hardfix된 네임스페이스 지정가능하도록 수정내역 반영
급하지는 않습니다. lma를 lma가 아닌 다른 네임스페이스로 설치하려면 필요합니다.
> lma-addons: bumpup

- lma/base/resources.yaml
- lma/base/site-values.yaml
1. thanos queryfrontend 서비스의 노드포트 지정관련 코드속의 유령을 잡았는데 역시 착각 이었음
- service.nodeports.http 라니...
2. minio의 재시작 정책관련 이슈도 찾았음
- ``` a.b = x ```와 
```
a:
b: x
```
가 다르게 적용되는 케이스였음, kustomize와 helm value 지정을 통과하면서 이걸 버그라과 봐야할지 의도된 것인지 모르겠음  
혼선을 없애기 위해 site에 잘못된 부분도 바로잡음..  https://github.com/openinfradev/decapod-site/pull/211
> Bugfix skb

- tks-cluster/infra/aws/resources.yaml
https://github.com/openinfradev/helm-charts/pull/219 내용 반영합니다.
> tks-cluster: aws: update capa chart to v0.10.0

- lma/base/resources.yaml
node exporter에서 수집하는 데이터에 호스트명을 추가합니다.
이렇게 되면 추후 노드관련 매트릭 (ex. node_cpu_throttle ?, node_load_1....)에는 라벨들 중 hostname이라는 필드에 해당 머신의 hostname이 들어갑니다. 
hostname을 영구적으로 적용한게 아니라면 이에 따른 시계열 데이터 분리(기존 호스트명 데이터와 바뀐 호스트명 데이터)가 있을수 있습니다.
이후 작업으로 기존에 instance를 기준으로 호스트를 판단했던 grafana dashboard들이 추가된 라벨을 사용하도록 수정하는 것을 권장합니다.
Base의 수정이므로 이것만 반영되면 이후 만들어지는 모든 클러스터에 반영됩니다.
> 노드 매트릭에 호스트명 추가

- tks-cluster/infra/aws/resources.yaml
psnm 지원을 위해 cluster-api-aws chart 버전을 업데이트 합니다.
helm-chart PR
. https://github.com/openinfradev/helm-charts/pull/221
> update chart version cluster-api-aws

- lma/base/resources.yaml
- lma/base/site-values.yaml
- tks-cluster/base/resources.yaml
- https://github.com/openinfradev/decapod-base-yaml/pull/304
- https://github.com/openinfradev/helm-charts/pull/223
> argo-rollout의 Servicemonitor 처리 (argo-rollouts chart -> lma-addons)

- lma/base/resources.yaml
fluentbit을 통한 알람발생을 더이상 지원하지 않습니다.
> fluentbit: does not support alert anymore

- lma/base/resources.yaml
전체적으로 namespace 지정하는 부분에 대해 문제가 있습니다.
namespace는 
- base-yaml의 resource과
- 배포(deploy)시 지정
두가지가 있는데 첫번째 지정된 내역으로 rendering이 수행되고 배포는 강제로 변경되는 형태로 동작됨
helm 배포는 두가지가 동시에 이뤄짐에 비해 오해의 소지가 발생함 
현 pr도 동일한 이슈에서 발생한 것으로 모든 helm chart에서 이러한 문제를 잠재적으로 갖고 있음
helmchart 내부에 여러가지 자원들 중 namespace를 랜더링시 yaml로 기록하는 내역들이 있는데 이것도 serviceaccount를 랜더링시 사용한 네임스페이스에 고정했는데 workflow에서 다른 네임스페이스를 지정함으로써 발생함
따라서 추후에는 네임스페이스 통합이 필요함!!!
> policy-serving: change the namespace for decapod randering

- lma/base/resources.yaml
이전 commit에서 위치가 잘못되어 다시 pr
policy-serving: change the namespace for decapod randering
> typo-fix: policy-serving: change the namespace for decapod randering

- lma/base/resources.yaml
fluentbit 3.0 버전을 사용합니다.
현재 2.2 버전에 버그가 있는듯 합니다. 긴급패치까지 포함해야됨.
> fluentbit: use upgraded version from 2.2 to 3.0

- policy/base/resources.yaml
- policy/base/site-values.yaml
SBOM을 통한 정책생성을 위한 모듈(ratify)을 설치합니다.
기존 모듈과 상충은 없음, site-value로 실 적용시 적용할 값의 예시를 정의 (인증서, 검출 룰) 
이를 기반으로 할수 있는 기능예시
- GPL 라이센스 기반 오픈소스사용 금지
- AGPL 라이센스 기반 오픈소스사용 금지
- 특정 오픈소스 사용금지 등..
> tks-policy: add ratify for supporting valication upon SBOM.

- lma/base/resources.yaml
- lma/base/site-values.yaml
아래내역은 세트임
- https://github.com/openinfradev/helm-charts/pull/240
- https://github.com/openinfradev/tks-flow/pull/377
- https://github.com/openinfradev/decapod-site/pull/242
- https://github.com/openinfradev/decapod-base-yaml/pull/323
> User logging 지원

- lma/base/resources.yaml
- lma/base/site-values.yaml
- policy/base/resources.yaml
- policy/base/site-values.yaml
- tks-cluster/infra/aws/resources.yaml
- tks-cluster/infra/aws/site-values.yaml
> 20241002 release from develop

- lma/base/resources.yaml
clusterName으로 url과 클러스터 표기를 병행했던것을 명확하게 분리
- 현재 클러스터명을 url에 넣지 못하는 이슈가 있어, 이에대한 회피를 통해 잠재적인 에러들을 만들고 있었음
> lma: seperate clusterName and clusterDomain explicitly
